- name: Install VS Code
  become: true
  become_user: aur-builder
  aur:
    name: visual-studio-code-bin

- name: Install VS Code extensions
  ansible.builtin.command:
    cmd: "code --install-extension {{ item }}"
  register: vscode__internal_extinstall
  loop: "{{ vscode__extensions }}"
  changed_when: not 'already installed' in vscode__internal_extinstall.stdout

- name: Configure code-flags for Wayland
  ansible.builtin.copy:
    src: "{{ role_path }}/files/code-flags.conf"
    dest: "{{ env__home_dir }}/.config/code-flags.conf"
    mode: "u=rw,g=r,o=r"
