env__user: marc
env__home_dir: "/home/{{ env__user }}"
env__rcfile: "{{ env__home_dir }}/.zsh/zshrc.local.zsh" # Shell RC file (bashrc, zshrc, etc) for sourcing scripts
env__github_ssh_key: "{{ env__home_dir }}/.ssh/id_ed25519" # SSH key to use for github clones

bootstrap_pacman_packages:
  - base-devel
  - git
  - python
  - python-psutil
  - sshpass
  - go

vscode__extensions:
  - be5invis.vscode-icontheme-nomo-dark # Nomo Dark icon theme
  - davidanson.vscode-markdownlint
  - eamodio.gitlens
  - ms-azuretools.vscode-docker
  - ms-kubernetes-tools.vscode-kubernetes-tools
  - ms-python.black-formatter
  - ms-python.flake8
  - ms-python.isort
  - ms-python.python
  - ms-vscode-remote.remote-containers
  - golang.Go
  - redhat.ansible
  - redhat.vscode-yaml
  - mechatroner.rainbow-csv
  - EditorConfig.EditorConfig
  - samuelcolvin.jinjahtml
  - VisualStudioExptTeam.vscodeintellicode
  - yzhang.markdown-all-in-one
  - zhuangtongfa.material-theme # One Dark Pro color theme

dotfiles__path: "{{ env__home_dir }}/.dotfiles"
