env__user: marc
env__home_dir: "/home/{{ env__user }}"
env__rcfile: "{{ env__home_dir }}/.zsh/zshrc.local.zsh" # Shell RC file (bashrc, zshrc, etc) for sourcing scripts
env__github_ssh_key: "{{ env__home_dir }}/.ssh/id_ed25519" # SSH key to use for github clones

bootstrap_pacman_packages:
  - base-devel
  - git
  - python
  - python2
  - python-psutil
  - go

vscode__extensions:
  - vscoss.vscode-ansible
  - zhuangtongfa.material-theme # One Dark Pro color theme
  - be5invis.vscode-icontheme-nomo-dark # Nomo Dark icon theme
  - eamodio.gitlens
  - davidanson.vscode-markdownlint
  - peterjausovec.vscode-docker
  - ms-vscode.go
  - samuelcolvin.jinjahtml

dotfiles__path: "{{ env__home_dir }}/.dotfiles"
