env__home_dir: /home/marc

bootstrap_pacman_packages:
  - base-devel
  - git
  - python
  - python2
  - python-psutil
  - go

vscode__extensions:
  - vscoss.vscode-ansible
  - zhuangtongfa.material-theme # One Dark Pro color theme
  - be5invis.vscode-icontheme-nomo-dark # Nomo Dark icon theme
  - eamodio.gitlens
  - peterjausovec.vscode-docker
  - davidanson.vscode-markdownlint

dotfiles__path: "{{ env__home_dir }}/.dotfiles"
