- hosts: localhost
  name: Install GUI applications
  tasks:
    - name: Install apps from pacman
      become: true
      community.general.community.general.pacman:
        name:
          - firefox
          - gparted
          - libreoffice-fresh
          - telegram-desktop

    - name: Install apps from AUR
      become: true
      become_user: aur-builder
      aur:
        name: "{{ item }}"
      loop:
        - 1password
        - gnome-browser-connector
        - gnome-shell-extension-dash-to-dock
        - google-chrome
        - insync
        - insync-nautilus
        - lens-bin
