- hosts: localhost
  tasks:
    - name: Install apps from pacman
      become: true
      pacman:
        name:
          - telegram-desktop
          - libreoffice-fresh
          - gparted

    - name: Install apps from AUR
      become: yes
      become_user: aur-builder
      aur:
        name: "{{ item }}"
      loop:
        - google-chrome
        - lastpass
        - gpmdp
        - typora
        - dropbox
        - nautilus-dropbox
        - insync
        - insync-nautilus
