- hosts: localhost
  name: Install filesystems support
  tasks:
    - name: Install filesystem packages
      become: true
      community.general.pacman:
        name:
          - exfat-utils  # exFAT
          - ntfs-3g      # NTFS
          - e2fsprogs    # ext2/3/4
          - dosfstools   # vFAT
