- hosts: localhost
  tasks:
    - name: Install GNOME packages from pacman
      become: yes
      pacman:
        name:
          - dconf-editor
          - flatpak
          - gnome
          - gnome-software-packagekit-plugin
          - gnome-tweaks
          - xdg-desktop-portal-gnome

    - name: Install font packages
      become: yes
      pacman:
        name:
          - adobe-source-code-pro-fonts
          - adobe-source-han-sans-otc-fonts
          - adobe-source-han-serif-otc-fonts
          - adobe-source-sans-pro-fonts
          - adobe-source-serif-pro-fonts
          - noto-fonts
          - noto-fonts-cjk
          - noto-fonts-emoji
          - ttf-jetbrains-mono-nerd
          - ttf-liberation

    - name: Install icons from AUR
      become: yes
      become_user: aur-builder
      aur:
        name: "{{ item }}"
      loop:
        - numix-circle-icon-theme-git
        - numix-icon-theme-git

    - name: Set GNOME settings
      dconf:
        key: "{{ item.key }}"
        value: "{{ item.value }}"
        state: present
      with_dict:
        /org.gnome.desktop.interface/clock-show-date: "true"
        /org/gnome/desktop/interface/icon-theme: "'Numix-Circle'"
        /org/gnome/desktop/interface/font-name: "'Source Sans Pro 13'"
        /org/gnome/desktop/interface/monospace-font-name: "'Source Code Pro 12'"
        /org/gnome/desktop/interface/document-font-name: "'Source Sans Pro 12'"
        /org/gnome/desktop/interface/clock-show-date: "true"
        /org/gnome/mutter/center-new-windows: "true"
        /org/gnome/terminal/legacy/new-terminal-mode: "'tab'"
        /org/gnome/terminal/legacy/theme-variant: "'dark'"
