- hosts: localhost
  tasks:
    - name: Install GNOME packages from pacman
      become: yes
      pacman:
        name:
          - gnome
          - dconf-editor
          - gnome-tweaks
          - gnome-software-packagekit-plugin
          - flatpak
          - xdg-desktop-portal-gtk

    - name: Install font packages
      become: yes
      pacman:
        name:
          - adobe-source-code-pro-fonts
          - adobe-source-sans-pro-fonts
          - adobe-source-serif-pro-fonts
          - adobe-source-han-sans-otc-fonts
          - adobe-source-han-serif-otc-fonts
          - noto-fonts
          - noto-fonts-emoji
          - noto-fonts-cjk
          - ttf-liberation

    - name: Install themes
      become: yes
      pacman:
        name:
          - arc-solid-gtk-theme

    - name: Install icons from AUR
      become: yes
      become_user: aur-builder
      aur:
        name: "{{ item }}"
      loop:
        - numix-icon-theme-git
        - numix-circle-icon-theme-git
        - numix-square-icon-theme-git

    - name: Set GNOME settings
      dconf:
        key: "{{ item.key }}"
        value: "{{ item.value }}"
        state: present
      with_dict:
        /org/gnome/desktop/interface/gtk-theme: "'Arc-Darker-solid'"
        /org/gnome/desktop/interface/icon-theme: "'Numix-Circle'"
        /org/gnome/desktop/interface/font-name: "'Source Sans Pro 13'"
        /org/gnome/desktop/interface/monospace-font-name: "'Source Code Pro 12'"
        /org/gnome/desktop/interface/document-font-name: "'Source Sans Pro 12'"
        /org/gnome/desktop/interface/clock-show-date: "true"
        /org/gnome/mutter/center-new-windows: "true"
        /org/gnome/shell/extensions/user-theme/name: "'Arc-Dark-solid'"
        /org/gnome/terminal/legacy/default-show-menubar: "false"
        /org/gnome/terminal/legacy/new-terminal-mode: "'tab'"
        /org/gnome/terminal/legacy/theme-variant: "'dark'"
