- hosts: localhost
  tasks:
    - name: Install go tools from pacman
      become: yes
      pacman:
        state: present
        name:
          - go

    # See: https://github.com/Microsoft/vscode-go/wiki/Go-tools-that-the-Go-extension-depends-on
    # Always marked as "changed" (command module)
    - name: Install Go dev packages
      command: "go get -v -u {{ item }}"
      loop:
        - golang.org/x/tools/cmd/guru
        - golang.org/x/tools/cmd/gorename
        - github.com/ramya-rao-a/go-outline
        - github.com/newhook/go-symbols
        - github.com/uudashr/gopkgs/cmd/gopkgs
        - github.com/golangci/golangci-lint/cmd/golangci-lint
        - github.com/mgechev/revive
        - github.com/go-delve/delve/cmd/dlv
