- hosts: localhost
  name: Install Go development tooling
  tasks:
    - name: Install Go tools from pacman
      become: true
      community.general.pacman:
        state: present
        name:
          - go
