# Install the Java development environment
- hosts: localhost
  become: yes
  tasks:
    - name: Install java JDKs
      pacman:
       name: jdk-openjdk jdk8-openjdk
       state: present

    - name: Install Java build tools
      pacman:
        name: maven gradle ant
        state: present
