- hosts: localhost
  name: Install JS development tooling
  tasks:
    - name: Install JS packages from pacman
      become: true
      community.general.pacman:
        name:
          - nodejs
          - npm

    - name: Install JS tools from AUR
      become: true
      become_user: aur-builder
      aur:
        name: "{{ item }}"
      loop:
        - nvm

    - name: Create NVM dir
      ansible.builtin.file:
        state: directory
        path: "{{ env__home_dir }}/.nvm"
        mode: "u=rwx,g=rx,o=rx"

    - name: Add NVM sourcing to rc file
      ansible.builtin.blockinfile:
        path: "{{ env__rcfile }}"
        create: true
        state: present
        mode: "u=rw,g=r,o=r"
        marker: "# ANSIBLE - nvm - {mark}"
        block: |-
          # Set up Node Version Manager
          export NVM_DIR="$HOME/.nvm"
          export NVM_SOURCE="/usr/share/nvm" # AUR package location
          [ -s "$NVM_SOURCE/nvm.sh" ] && . "$NVM_SOURCE/nvm.sh"
