# Install the Java development environment
- hosts: localhost
  become: yes
  tasks:
    - name: Install java JDKs
      pacman:
       name: jdk-openjdk jdk11-openjdk jdk8-openjdk
       state: present

    - name: Install Java build tools
      pacman:
        name: maven gradle ant
        state: present

    - name: Install Kotlin tooling
      pacman:
        name: kotlin
        state: present

    - name: Install Scala tooling
      pacman:
        name: scala-docs scala-sources sbt
        state: present
