- hosts: localhost
  name: Install JVM development tooling
  become: true
  tasks:
    - name: Install java JDKs (LTS + latest)
      community.general.pacman:
        state: present
        name:
          - jdk-openjdk
          - openjdk-doc
          - openjdk-src
          - jdk17-openjdk
          - openjdk17-doc
          - openjdk17-src
          - jdk11-openjdk
          - openjdk11-doc
          - openjdk11-src

    - name: Install Java build tools
      community.general.pacman:
        state: present
        name:
          - maven
          - gradle
          - ant

    - name: Install Kotlin tooling
      community.general.pacman:
        name: kotlin
        state: present
