- hosts: localhost
  become: yes
  tasks:
    - name: Install java JDKs
      pacman:
       state: present
       name:
        - jdk-openjdk
        - jdk11-openjdk
        - jdk8-openjdk

    - name: Install Java build tools
      pacman:
        state: present
        name:
          - maven
          - gradle
          - ant

    - name: Install Kotlin tooling
      pacman:
        name: kotlin
        state: present

    - name: Install Scala tooling
      pacman:
        state: present
        name:
          - scala-docs
          - scala-sources
          - sbt
