- hosts: localhost
  tasks:
    - name: Install Kubernetes tools from pacman
      become: yes
      pacman:
        name:
          - kubectl
          - minikube
          - kubectx
          - helm
          - k9s
        state: present

    - name: Install Kubernetes tools from AUR
      become: yes
      become_user: aur-builder
      aur:
        name: "{{ item }}"
      loop:
        - kind-bin
        - kompose-bin
        - lens-bin

    - name: Configure minikube
      command: "minikube config set {{ item.key }} {{ item.value }}"
      with_dict:
        memory: 4096
        vm-driver: kvm2
      changed_when: false  # otherwise always marked as changed
