- hosts: localhost
  name: Install Kubernetes tooling
  tasks:
    - name: Install Kubernetes tools from pacman
      become: true
      community.general.pacman:
        name:
          - kubectl
          - kustomize
          - minikube
          - kubectx
          - helm
          - k9s
        state: present

    - name: Install Kubernetes tools from AUR
      become: true
      become_user: aur-builder
      aur:
        name: "{{ item }}"
      loop:
        - kind-bin

    - name: Configure minikube
      ansible.builtin.command: "minikube config set {{ item.key }} {{ item.value }}"
      with_dict:
        memory: 4096
        vm-driver: kvm2
      changed_when: false # otherwise always marked as changed
