# Configure Shell
- hosts: localhost
  tasks:
    - name: Install basic shell packages
      become: yes
      pacman:
        state: present
        name:
          - zsh
          - zsh-completions
          - bash-completion

    - name: Install command-line utilities
      become: yes
      pacman:
        state: present
        name:
          - bat
          - exa
          - fd
          - git-delta
          - htop
          - jq
          - ripgrep
          - starship
          - thefuck
          - tldr
          - tree
          - vim
          - zoxide

    - name: Install base16-shell
      git:
        repo: git@github.com:chriskempson/base16-shell.git
        dest:  "{{ env__home_dir }}/.config/base16-shell"
        key_file: "{{ env__github_ssh_key }}"
        accept_hostkey: yes

    - name: Install my dotfiles
      git:
        repo: git@github.com:mdemierre/dotfiles.git
        dest: "{{ dotfiles__path }}"
        key_file: "{{ env__github_ssh_key }}"
        accept_hostkey: yes
      tags:
        - dotfiles

    - name: Link dotfiles
      file:
        src: "{{ dotfiles__path }}/{{ item.src }}"
        dest: "{{ env__home_dir }}/{{ item.dest }}"
        state: link
      loop:
        - src: git/gitconfig
          dest: .gitconfig
        - src: vim/vimrc
          dest: .vimrc
        - src: bat
          dest: .config/bat
        - src: starship.toml
          dest: .config/starship.toml
      tags:
        - dotfiles


    - name: Install command-line utilities from AUR
      become: yes
      become_user: aur-builder
      aur:
        name: "{{ item }}"
      loop:
        - vim-plug
      tags:
        - dotfiles

    - name: Install vim plugins
      command: "vim :PlugInstall +qall"
      tags:
        - dotfiles

    - name: Install my prezto fork
      git:
        repo: git@github.com:mdemierre/prezto.git
        version: mdemierre-customizations
        recursive: yes
        dest: "{{ env__home_dir }}/.zprezto"
        key_file: "{{ env__github_ssh_key }}"
        accept_hostkey: yes
      tags:
        - prezto

    - name: Activate prezto
      file:
        src: "{{ item }}"
        dest: "{{ env__home_dir }}/.{{ item | basename }}"
        state: link
      with_fileglob: "{{ env__home_dir }}/.zprezto/runcoms/z*"
      tags:
        - prezto
