- hosts: localhost
  tasks:
    - name: Install VM runtimes
      become: yes
      pacman:
        state: present
        name:
          # QEMU/KVM/libvirt
          - qemu
          - libvirt
          - dnsmasq
          - ebtables
          - dmidecode
          - bridge-utils
          - gnu-netcat
          # Virtualbox
          - virtualbox
          - virtualbox-host-modules-arch
          - virtualbox-guest-iso

    - name: Install VM tools from pacman
      become: yes
      pacman:
        state: present
        name:
          - vagrant
          - packer

    - name: Install VM tools from AUR
      become: yes
      become_user: aur-builder
      aur:
        name: "{{ item }}"
      loop:
        - virtualbox-ext-oracle

    - name: Add user to VM-related groups
      become: yes
      user:
        name: "{{ env__user }}"
        append: yes
        groups:
          - vboxusers # vbox - USB access
          - libvirt   # libvirt - passwordless management

    - name: Ensure libvirtd is enabled and started
      systemd:
        name: "libvirtd"
        state: started
        enabled: yes
