- hosts: localhost
  name: Setup VM runtimes and tooling
  tasks:
    - name: Install VM runtimes
      become: true
      community.general.pacman:
        state: present
        name:
          # QEMU/KVM/libvirt
          - qemu
          - libvirt
          - dnsmasq
          - ebtables
          - dmidecode
          - bridge-utils
          - gnu-netcat

    - name: Add user to VM-related groups
      become: true
      ansible.builtin.user:
        name: "{{ env__user }}"
        append: true
        groups:
          - vboxusers # vbox - USB access
          - libvirt   # libvirt - passwordless management

    - name: Ensure libvirtd is enabled and started
      ansible.builtin.systemd:
        name: "libvirtd"
        state: started
        enabled: true
